id: IEB9656F8
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:20:20.478789+00:00
last_modified: 2022-12-14 18:20:20.478797+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-046-002
  eft-text-version: 1.3.4 2020
  title: Toh_96-The_Miraculous_Play_of_Manjusri-v2
bases:
  19F5:
    source_metadata: null
    order: 1
    base_file: 19F5.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
